name: release 

on: 
  push:
    tags:
      - v*
  pull_request:
    branches: ["**"]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  build-analyze-push:
    name: Build, Analyze, Push
    runs-on: ubuntu-latest

    steps:
      - name: Setup the QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Multi-platform Docker Build and Push to registry
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          load: false # docker exporter does not currently support exporting manifest lists
          sbom: true
          provenance: true
          platforms: linux/amd64,linux/arm64
          tags: |
           ghcr.io/${{ github.repository_owner }}/${{ matrix.service }}-dumpstore:${{ github.sha }}
